### PR TITLE
Feature: provide option to show console.logs from preprocessors

### PR DESCRIPTION
**Pull request by sebastianrothe**
This will undo https://github.com/mihar-22/svelte-jester/pull/50 because it swallowed an error described here https://github.com/mihar-22/svelte-jester/issues/47#issuecomment-858122652

### CODE REVIEW

**Comment by sebastianrothe** [comment]
Maybe we should put in a switch to active the console.logs instead.

**Comment by sebastianrothe** [comment]
> Maybe we should put in a switch to active the console.logs instead.

I changed the code to use an option.

**Comment by mihar-22** [comment]
LGTM

**Comment by sebastianrothe** [comment]
I'm so sorry, but I disabled most of the tests with one commit :(

https://github.com/mihar-22/svelte-jester/pull/53/files#diff-f638d82910738e07f34f9ca5c6cb2a01c223570f9c2425ddf60f61e2070c169dR64

**Comment by sebastianrothe** [comment]
> I'm so sorry, but I disabled most of the tests with one commit :(
> 
> https://github.com/mihar-22/svelte-jester/pull/53/files#diff-f638d82910738e07f34f9ca5c6cb2a01c223570f9c2425ddf60f61e2070c169dR64

fixed in https://github.com/mihar-22/svelte-jester/pull/57

**Pull request merged**
