### PR TITLE
Add preprocess to published files array

### LINKED ISSUE #81: Cannot find module './preprocess.js'
First off @mihar-22 @benmccann Thanks for the quick release of 2.1.3! And everyone else who got that through - much appreciated with the quick turnaround. This might be something obvious I'm missing but while the transform export issue has been solved I'm now getting an issue with the preprocess.js file which doesn't seem to exist or be copied into dist. I see that #71 added the command to copy to dist from src/preprocess.js but I'm not seeing it in the final build.

Is there something I need to make sure I'm doing to make this work? I know it's been noted that the fixes for 2.1.3 had been tested in a few places and were working so guessing it's something on my end. Any nudge in the right direction would be great. Thanks!

### PR DESCRIPTION
**Pull request by sebastianrothe**
add preprocess to published files

Fixes #81

### CODE REVIEW

**Comment by mihar-22** [comment]
Why did `package-lock.json` completely change? What version of NPM are you using? Prefer NPM `>=7` to use v2 lockfiles. Is this related to something else? By the way maybe we should include the entire dist folder `dist/`?

**Review by benmccann — APPROVED** [review]

**Comment by sebastianrothe** [comment]
> Why did `package-lock.json` completely change? What version of NPM are you using? Prefer NPM `>=7` to use v2 lockfiles. Is this related to something else? By the way maybe we should include the entire dist folder `dist/`?

Well I am using the latest npm v7 and lockfile v2. Someone else committed an old lockfile.

**Comment by sebastianrothe** [comment]
@mihar-22 Please publish a new version. I think this time it is correct :)

**Comment by sebastianrothe** [comment]
> I agree that including the entire `dist` directory would be a better solution

I added one more commit.

**Comment by benmccann** [comment]
@mihar-22 it looks like you might be on npm 6. It got switched to the old lockfile format here: https://github.com/mihar-22/svelte-jester/commit/c59643a71261d086063eb128fb51e19c0da93514

Anyway, this looks good to me! Thanks for helping to work through these issues and get new versions out!

**Comment by sebastianrothe** [comment]
Somehow the [lockfile](https://github.com/mihar-22/svelte-jester/blob/master/package-lock.json) is v1 again. Is NPM doing this?

**Comment by mihar-22** [comment]
Ah I know why... I always try to run the tests but they fail on Node 16/NPM 7 due to SASS compiler not working with that version on the new ARMx64 architecture. So after that fails I switch to Node 14 and it works. It's the only way I can verify tests. I'll move releases to CI to resolve this, but we need to ensure commits follow standard semantic-release conventions, so probabaly need to add commitlint.

**Comment by sebastianrothe** [comment]
The tests do run in the CI, too.

But a release from the CI would be very nice :)

**Pull request merged**
