### PR TITLE
Support SvelteKit

### LINKED ISSUE #44: Svelte-kit support
Currently svelte-kit requires ```"type": "module"``` to be present in `package.json`. This does not work with current version of svelte-jester because it uses require under the hood and requires are prohibited with ES modules

### PR DESCRIPTION
**Pull request by sebastianrothe**
The main problem was, that cosmiconf could not import ESmodules within the `svelte.config.js` from SvelteKit. SvelteKit requires these imports (e.g. adapter) to be in ESM format. That's why the preprocess file has to be in ESM format as well. All other files still have to be commonJS, because otherwise jest won't be able to call them from the transformer (this might change in jest next).

To support ESmodules I had to bump the node version to 14+. It might be possible to call node with some experimental flags, if someone needs to use and old version of node. I thought v10 is deprecated and v14 is the current LTS version, so it is okay to require v14.

Jest won't understand ESM natively and so we need to transform ESmodules files with esbuild/babel. For this to work, I had to introduce a jest config file. I used [jest-circus](https://github.com/facebook/jest/tree/master/packages/jest-circus) as the new runner and added [v8](https://jestjs.io/docs/configuration#coverageprovider-string) as a provider which understands ESM as well.

Since the config files from Svelte and SvelteKit differ so much, I had to duplicate all tests to cover both scenarios.

**notable changes:**
-  added vscode extension recommendations and settings
- renamed js files to cjs
- duplicated tests for svelte and sveltekit (moved test suite into a base file)
- removed cosmiconf (node can import them dynamically)
- extract compiler from transformer to be able to reuse more code for the async transfomer #25 

I hope it still works for all people and settings out there. The tests run and our project with SvelteKit does as well.

This is also a preparation for #25 where we can try to convert all files to ESM and then use the async transformer from the next jest version.

Fixes #44 and #6

### CODE REVIEW

**Comment by mihar-22** [comment]
This is awesome, thanks @sebastianrothe! I'm out of the loop on all of this so if I understand correctly this will only work with Jest 27+? I'm considering releasing it as a breaking change so major bump.

**Comment by sebastianrothe** [comment]
> This is awesome, thanks @sebastianrothe! I'm out of the loop on all of this so if I understand correctly this will only work with Jest 27+? I'm considering releasing it as a breaking change so major bump.

No, this has been tested with Jest v26.

**Comment by mihar-22** [comment]
LGTM!

**Comment by mihar-22** [comment]
Thanks again for the PR @sebastianrothe. I've released everything in `1.6.0` 👍

**Comment by sebastianrothe** [comment]
> Thanks again for the PR @sebastianrothe. I've released everything in `1.6.0` 👍

Thanks! If there are any issues, I will gladly provide some support.

**Comment by jwrunner** [comment]
I upgraded from 1.5.0 to 1.6.0 and am having my very simple Hello component test failing now. Here is the [error](https://gist.github.com/jwrunner/b73446f0b983b974c3d2c4d72c6ab7cd) and my jest config is seen at https://github.com/HVSBible/hvsb/blob/main/tests/jest.svelte.cjs#L20 - note that I'm using a workaround dummy svelte config. Using that with 1.6.0 or also the `preprocess: true` option both throw the same error.

**Comment by sebastianrothe** [comment]
> I upgraded from 1.5.0 to 1.6.0 and am having my very simple [Hello component test](https://github.com/HVSBible/hvsb/blob/7306352cb14c3d6e62c6d351065908b3153c2637/src/lib/components/Hello.spec.ts) failing now. Here is the [error](https://gist.github.com/jwrunner/b73446f0b983b974c3d2c4d72c6ab7cd) and my jest config is seen at https://github.com/HVSBible/hvsb/blob/main/tests/jest.svelte.cjs#L20 - note that I'm using a workaround dummy svelte config. Using that with 1.6.0 or also the `preprocess: true` option both throw the same error.

No problems for me with your repo on Node 16. What version of node do you have ?

**Comment by sebastianrothe** [comment]
> > I upgraded from 1.5.0 to 1.6.0 and am having my very simple [Hello component test](https://github.com/HVSBible/hvsb/blob/7306352cb14c3d6e62c6d351065908b3153c2637/src/lib/components/Hello.spec.ts) failing now. Here is the [error](https://gist.github.com/jwrunner/b73446f0b983b974c3d2c4d72c6ab7cd) and my jest config is seen at https://github.com/HVSBible/hvsb/blob/main/tests/jest.svelte.cjs#L20 - note that I'm using a workaround dummy svelte config. Using that with 1.6.0 or also the `preprocess: true` option both throw the same error.
> 
> I see. Will have a look tonight.

@jwrunner If i run your repo with `preprocess: true`, it works for me (node 16). Btw, I think you don't need your `https://github.com/HVSBible/hvsb/blob/main/tests/jest-config-hack/svelte.config.js` anymore. 1.6.0 supports EMS config files.

**Comment by sebastianrothe** [comment]
Discussion continues in #47

**Comment by sebastianrothe** [comment]
@jwrunner Can you try again with version `1.7.0`, please ?

**Comment by jwrunner** [comment]
> @jwrunner Can you try again with version `1.7.0`, please ?

That fixed things. Thanks! I was traveling.

**Pull request merged**
